packages:
  - apps/*
  - packages/*
  - prisma

ignoredBuiltDependencies:
  - '@prisma/engines'
  - core-js
  - esbuild
  - msw
  - protobufjs
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - prisma
